import Head from "next/head";
import TopBar from "../components/TopBar";
import About from "~/components/About";
import Projects from "~/components/Projects";
import Skills from "~/components/Skills";
import Education from "~/components/Education";

export default function Home() {
  return (
    <>
      <Head>
        <title>Colm Lang</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen bg-canvas text-fgDefault">
        <TopBar />
        <div className="max-w-[1200px] mx-auto">
          <About />
          <Education />
          <Skills />
          <Projects />
        </div>
      </main>
    </>
  );
}
