import Head from "next/head";
import TopBar from "../components/TopBar";
import Category from "~/components/Category";
import About from "~/components/About";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen bg-canvas">
        <TopBar />
        <div className="max-w-[1200px] mx-auto">
          <About />
          <Category title="Projects">
            <div className="flex flex-col gap-8 h-screen">
            </div>
          </Category>
        </div>
      </main>
    </>
  );
}
